---
title: "Euclidean distance and its projection"
author: "Andrea Sánchez Tapia"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
library(rJava)
library(raster)
#library(ModelR)
devtools::load_all("../../modleR")
library(dplyr)
```

# Dataset

```{r dataset}
## Creating an object with species names
especies <- names(coordenadas)[1]
# Selecting only coordinates for the first species
coord1sp <- coordenadas[[1]]
head(coord1sp)
dim(coord1sp)
# Subsetting data into training and test
ceiling(0.7 * nrow(coord1sp))
# Making a sample of 70% of species' records
set <- sample(1:nrow(coord1sp), size = ceiling(0.7 * nrow(coord1sp)))
# Creating training data set (70% of species' records)
train_set <- coord1sp[set,]
# Creating test data set (other 30%)
test_set <- coord1sp[setdiff(1:nrow(coord1sp),set),]
```

# Fitting and projection datasets


```{r vars, message = F, eval = T}
fit_data <- raster::stack("../data/env/cropped_proj.tif")
```

```{r centroide}

centroide1 <- modleR::euclidean(predictors = example_vars,
                                occurrences = train_set[,c(2,3)],
                                algo = "centroid")
centroide2 <- modleR::euclidean(predictors = fit_data,
                                occurrences = train_set[,c(2,3)],
                                algo = "centroid")
plot(centroide1)
plot(centroide2)
points(train_set[,c(2,3)])

```

```{r mindist}

mindist1 <- modleR::euclidean(predictors = example_vars,
                              occurrences = train_set[,c(2,3)],
                              algo = "mindist")
mindist2 <- modleR::euclidean(predictors = fit_data,
                              occurrences = train_set[,c(2,3)],
                              algo = "mindist")

plot(mindist1)
points(train_set[,c(2,3)])
plot(mindist2)
points(train_set[,c(2,3)])
```


```{r cut, eval = F}
a <- rescale_layer(mindist1)
plot(a)
a > 0.8
plot(sort(values(a)))

plot(a > 0.95, main = "dist > 0.95", col = c("white", "green"))
plot(a > 0.99, main = "dist > 0.99", legend = F, add = T, col = c(NA, "red"))
maps::map(,,,add = T)

```


```{r, eval = F}
setup <- setup_sdmdata(species_name = especies[1],
                       occurrences = coord1sp[, -1],
                       predictors = fit_data,
                       models_dir = "./eucl")
```
```{r, eval = F}

centroid_no_proj <- do_any(species_name = especies[1],
                           predictors = fit_data,
                           write_png = T,
                           algo = "centroid",
                           models_dir = "./eucl")
mindist_no_proj <- do_any(species_name = especies[1],
                          predictors = fit_data,
                          write_png = T,
                          algo = "mindist",
                          models_dir = "./eucl")
```


## Compara a forma dos valores com domain e mahal

```{r}
centroide1 <- modleR::euclidean(predictors = example_vars,
                                occurrences = train_set[,c(2,3)],
                                algo = "centroid")
mahal1 <- dismo::mahal(x = example_vars,
                       p = train_set[,c(2,3)])
mahal1p <- predict(mahal1, example_vars)
par(mfrow = c(1, 2))
plot(mahal1p)
plot(centroide1)

plot(sort(values(centroide1)))
plot(sort(values(mahal1p)))
plot(sort(values(centroide1)), sort(values(mahal1p)))
```


```{r}
centroide_original <- modleR::euclidean(predictors = fit_data,
                                occurrences = train_set[,c(2,3)],
                                algo = "centroid")
mindist_original <- modleR::euclidean(predictors = fit_data,
                                occurrences = train_set[,c(2,3)],
                                algo = "mindist")
mahal_original <- dismo::mahal(x = fit_data,
                       p = train_set[,c(2,3)])
mahalp <- predict(mahal_original, fit_data)
par(mfrow = c(1, 3))
plot(mahalp)
plot(centroide_original)
plot(mindist_original)
```




```{r}
library(GGally)
df <- data.frame(cen = values(centroide_original), 
                 min = values(mindist_original), 
                 mah = values(mahalp))
ggpairs(df)


```

# cómo se distribuyen esos dados??

```{r}
Fn_cen <- ecdf(df$cen)
excen <- extract(centroide_original, coord1sp[,c(2,3)])
Fn_cen(min(excen))
#el LPT está en el quantil 42. 
Fn_min <- ecdf(df$min)
exmin <- extract(mindist_original, coord1sp[,c(2,3)])
Fn_min(min(exmin))
#el LPT de mindist está en el quantil 60. 
Fn_mah <- ecdf(df$mah)
exmah <- extract(mahalp, coord1sp[,c(2,3)])
Fn_mah(min(exmah))
#el LPT de mahal está en el quantil 67. la mayor parte de la distancia ni puta idea si sirve 
```

# centroide varia menos abruptamente
#o LPT fica em lugares diferentes

```{r}
par(mfrow = c(1, 3))
plot(sort(df$cen))
abline(v = sum(!is.na(df$cen))*Fn_cen(min(excen)), col = "red")

plot(sort(df$mah))
abline(v = sum(!is.na(df$mah))*Fn_mah(min(exmah)), col = "red")

plot(sort(df$min))
abline(v = sum(!is.na(df$min))*Fn_min(min(exmin)), col = "red")
```

```

# se eu cortar os três pela mediana

```{r}
par(mfrow = c(1,3))
meds <- apply(df, 2, median, na.rm = T)
q <- quantile(df$cen, 0.8, na.rm = T, names = F)

quant <- apply(df, 2, quantile, na.rm = T, probs = 0.8)
plot(centroide_original > meds["cen"])
plot(mindist_original > meds["min"])
plot(mahalp > meds["mah"])

centroide1 <- centroide_original
mindist1 <- mindist_original
mahalp1 <- mahalp

centroide1[centroide1 <= meds["cen"]] <- meds["cen"]
plot(centroide1)
mindist1[mindist1 <= meds["min"]] <- meds["min"]
plot(mindist1)
mahalp1[mahalp1 <= meds["mah"]] <- meds["mah"]
plot(mahalp1)


```

e se comparássemos isto a buffer?

```{r}
par(mfrow = c(1, 3))
plot(centroide_original > quant["cen"])
plot(mindist_original > quant["min"])
plot(mahalp1 > quant["mah"])

```

